development:
  adapter: sqlite
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: mock
  database: mock

production:
  adapter: THIS_FILE_WILL_BE_OVERWRITTEN_BY_HEROKU_ANYWAY